2024-Algorithm-9oormthon-univ/Algorithm-Study

a-honey/brute_force/소수찾기.py
a-honey/greedy/큰 수 만들기.py

> Greedy
매 단계에서 최적의 선택
> Brute_force
- 완전 탐색
가능한 모든 조합을 만들어 내고 소수인지 판단

a-honey / 1주차 / 2문제

---

howooyeon/bruet_force/카펫.java
howooyeon/greedy/조이스틱.java

> Greedy / Level 2
위아래로 조이스틱을 조작하는 횟수를 계산하고 변수 answer에 더함
좌우로 이동하는 최소한의 횟수 계산을 위해 move라는 변수를 만들고 최소 횟수를 계산한 뒤 move 변수를 갱신
마지막으로 answer에 좌우로 이동하는 횟수를 더한 후 결과 반환
> Brute_force / Level 2
가로의 길이 x, 세로의 길이 y라고 할 때, 카펫 둘레의 길이는 2(x + y) = brown + 4
공식을 통해 x = brown/2 + 2 - y 라고 선언해주고 y의 값을 1개씩 증감
이때 y값을 증감시켜 x값을 알아낸다면 x, y의 값을 알 수 있다.
while문 안에서 카펫의 넓이 공식으로 알아낸 수식으로 조건을 걸어준 뒤
참이라면 배열을 반환

howooyeon / 1주차 / 2문제

---

Grace/brute_force/카펫.py
Grace/greedy/조이스틱.py

> Greedy / Level 2
처음엔 ‘A’가 두 번째 위치(index = 1)에 있냐 없냐만 구분해서 있다면 역방향으로 for문을 돌리고, 없다면 정방향으로 for문을 돌려서 찾으면 되는 줄 알고 그렇게 풀었다가, A가 중간중간 껴져있다는 케이스를 생각하지 못했다. ex) JAAAEAAASAD 처럼.
그래서 그 다음 좌 우 와 상 하 부분을 각각 구분해서 더했다.
좌, 우 = 좌우이동 휫수는 길이의 -1
상, 하 = A를 기준으로 오른쪽과 왼쪽 각각 커서를 먼저 이동 후, 알파벳을 바꿔가며 반대 방향으로 이동하는 식으로 계산한다. 따라서 A를 기준으로 왼쪽 또는 오른쪽을 두 번 지나가기 때문에 2배 처리한 값 + 오른쪽(혹은 왼쪽)을 더한다.
> Brute_force / Level 2
처음에는 brown과 yellow의 합이 전체다 라는 것으로 합의 약수를 구해서 하려고 했으나... 그 후의 더 수식이 나오질 않아 다른 방법으로 풀었다.
그래서 그림을 보고 생각한 것이 `(yellow의 가로 길이 * 2) + (yellow의 세로길이 * 2) + 4` 값이 갈색 격자 수라는 것을 알게 되었다. 노란색의 수를 반복하면서 노란색 수가 i로 나누어 떨어질 때, 가로가 i로 나눈 몫, 그리고 세로가 i가 된다.(= 가로 * 세로의 수식처럼)
그 후 위의 수식을 이용하여 값을 구해주었다.

Grace / 1주차 / 2문제

---

daeun/brute_force/카펫.js
daeun/greedy/큰 수 만들기.js

**[PSG] 큰 수 만들기 / Level 2**
<hr>
**[PSG] 카펫 / Level 2**
<hr>

daeun / 1주차 / 2문제 

---

devjaeyoon/brute_force/카펫.js
devjaeyoon/greedy/큰 수 만들기.js
devjaeyoon/stack_queue/주식가격.js

> greedy
> stack_queue
> brute_force

devjaeyoon / 1주차 / 3문제

---

d15m4s/stack_queue/K번째 수.java
d15m4s/stack_queue/베스트엘범.java
d15m4s/stack_queue/주식가격.java
d15m4s/stack_queue/프로세스.java

카테고리 : 해시(1), 스택/큐(2), 정렬(1)
개선점 : 
1. 처음으로 cpp가 아닌 java로 코딩테스트를 진행했습니다. 그렇다보니 컬렉션(cpp 컨테이너)에 대한 이해가 많이 부족했습니다. 보다 정확한 최적화를 위해서는 컬렉션 프레임워크의 내부 구조에 대해서 보다 구체적으로 알 필요가 있어 보입니다.
2. 스트림 문법에 대한 이해가 많이 부족했습니다. java책을 뒤져가며 작성했던 기억이 납니다. 이 부분은 더 보강할 필요가 있어 보입니다.
3. 접근 방식을 보다 구체화 할 필요가 있습니다.

d15m4s / 2주차 / 4문제

---

howooyeon/dfs_bfs/네트워크.java
howooyeon/hash/의상.java
howooyeon/sort/K번째수.java
howooyeon/stack_queue/주식가격.java

> stack_queue / Level 2
먼저, answer 배열은 해당 가격이 유지된 기간을 저장할 배열
배열의 크기는 prices 배열의 길이와 동일
외부 루프에서는 배열의 각 요소를 순회
내부 루프에서는 외부 루프의 현재 인덱스 다음부터 배열 끝까지 순회하며 가격을 비교
내부 루프에서 현재 가격보다 낮은 가격이 나올 때까지 count++
만약 현재 가격보다 낮은 가격이 나온다면 내부 루프 break 다음 가격을 처리
이렇게 얻은 count 값을 answer 배열에 저장
answer 반환
> dfs_bfs / Level 3
visited라는 boolean 배열 선언해 각 컴퓨터 방문 여부 기록
count 변수 선언 후 0으로 초기화하여 네트워크 개수 세는데 사용
모든 컴퓨터를 순회하면서 방문하지 않은 컴퓨터(visited[i] == false) 찾기
방문하지 않은 컴퓨터를 발견하면 dfs 메소드 호출해 해당 컴퓨터와 연결된 모든 컴퓨터 방문
dfs 메소드 호출시 visited[i] == true, 방문한걸로 표시하고
모든 컴퓨터 순회해 현재 컴퓨터와 연결된, 아직 방문하지 않은 컴퓨터를 찾자 !!
코드로 보면 => (computers[node][i] == 1 && !visited[i])
해당 컴퓨터에 대해 재귀적으로 dfs를 호출하여 계속해서 탐색
> dfs_bfs / Level 2
HashMap을 사용하여 각 종류의 옷과 그에 해당하는 개수를 저장
모든 종류의 옷을 하나씩 순회, 각 종류별로 옷을 입거나 입지 않는 경우의 수를 곱하여 answer에 저장
이때, 옷을 입지 않는 경우도 포함하기 위해 각 …

howooyeon / 2주차 / 4문제

---

daeun/brute_force/카펫.js
daeun/dfs_bfs/타겟 넘버.js
daeun/hash/전화번호 목록.js
daeun/sort/K번째수.js
daeun/stack_queue/프로세스.js

**[PSG] K번째수 / Level1**
풀이 방법: 배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 구하기 위해서 slice( )와 sort( )를 이용해 리스트를 오름차순으로 정렬시키고 k번재 값을 뽑아 answer 배열에 추가해 해결했다.
<hr>
**[PSG] 전화번호 목록 / Level 2**
풀이 방법: 처음에는 배열의 첫번째 요소끼리 이중 for문을 사용해서 비교하면 되겠다는 단순한 생각으로 접근했다. 하지만 코드를 작성하니 복잡하고 보기 좋지 않아 더 나은 해결방법을 고민하던 중, 먼저 전화번호를 정렬시키고 연속된 두 번호만을 비교하고 startsWith을 이용하면 간단하게 첫 번째 요소만을 비교할 수 있다는 것을 알게 되어 쉽게 계산할 수 있었다.
* startsWith( ) : 문자열이 특정 문자열로 시작하는지 확인하는 메소드, 지정된 문자열로 시작하는 경우에 true를 반환하고 그렇지 않으면 false를 반환한다.
<hr>
**[PSG] 타겟 넘버 / Level 2**
풀이 방법: 재귀함수를 이용해 모든 경우의 수를 탐색해 값을 찾는 방법을 이용했다. 재귀함수 호출 시 코드의 접근 횟수를 제한하기 위해 index와 숫자들의 합을 담을 sum을 넘겨줬다. sum이 원하는 값에 도달하면 answer로 정답 횟수를 세고, 아니라면 sum값과 현재 인덱스의 값을 더한 값과 뺀 값을 인수로 주어 트리의 모든 인덱스를 탐색할 수 있도록 해서 풀었다.
<hr>
**[PSG] 프로세스 / Level 2**
풀이 방법: priorities 배열을 이용해 각 …

daeun / 2주차 / 4문제

---

imeureka/dfs_bfs/타겟넘버.js
imeureka/hash/의상.js
imeureka/sort/h-index.js
imeureka/stack_queue/같은숫자는싫어.js
imeureka/stack_queue/주식가격.js

> Dfs_Bfs / Level 2
DFS로 음수일 경우 일 때를 확인하기 위해 깊이를 탐색하는 dfs 탐색법으로 접근하였다. 그리고 예시를 보고 + - 경우의 수를 코드로 구현할 때 조금 막막했었는데, 함수를 두번 호출함으로써 모든 경우의 수를 생각할 수 있게되었다. 
> Hash / Level 2
Map 자료형으로 다시 [type, type의 수] 자료형을 만들어 문제에 접근하였다. 즉 
[하트선글라스, 안경], [별 안경, 안경], [깃털모자, 모자] 일 때 옷 종류에 따라 조합할 수 있는 경우의 수를 계산하도록 하였다. 처음엔 옷 종류별 개수를 Map에 저장하고 이미 있는 종류면 개수 증가, 새로운 종류라면 1로 초기화하고 각 종류별 옷을 입는 경우의 수 (해당 종류의 옷 개수 + 1)를 계산했다. 
> Stack_Queue / Level 2
처음에는 무슨소리인가 했다. 근데 재해석된 문제를 보고 한번에 이해완료했다. 
[주식가격문제](https://school.programmers.co.kr/questions/20326?question=20326)
> Sort / Level 2
1.sort 함수를 이용해 citations 배열을 정렬 특정 
2. 인덱스 i부터 citations배열의 길이까지 만큼의 논문이 citations[i]번 만큼 인용되었다.
3. citations[i]에서 i값을 증가시키고 논문의 수를 감소시키면서 비교 했을 때 인용 횟수가 논문의 수 이상이 되었을 때의 논문의 수가 H-Index가 된다

Imeureka / 2주차 / 4문제

---

a-honey/hash/전화번호_목록.py
a-honey/sort/K번째수.py
a-honey/stack_queue/주식가격.py

배열을 순서대로 반복하면서, 현재 인덱스의 가격보다 다음 인덱스의 가격이 더 낮을때까지 1씩 증가하는 변수를 만들고 낮은 지점이 올때 answer 배열에 추가했습니다.
처음에는 hash를 이용하기 위해 객체로 선언하였으나 정렬 후에 반복하여 확인하는 것이 더 빠를듯해 반복을 사용했습니다. 전화번호를 정렬한 후, 다음 인덱스의 번호가 현재 인덱스의 번호로 시작한다면 False를, 반복이 끝날때까지 prefix가 아니라면 True를 반환하였습니다.
2차원 배열로 구성된 commands를 하나씩 반복하면서 배열을 구조할당한 후, 주어진 array를 각 할당한 수만큼 잘라 정렬하였습니다. 이후 정렬한 배열에서 k번째 숫자를 answer 배열에 추가했습니다. 
처음에는 노드 트리 개념을 몰라서 어려웠는데, 깊이 우선 탐색 알고리즘에 대해서 학습하면서 개념 흐을 잡을 수 있었습니다.  먼저 네트워크 개수만큼 배열을 만들어 boolean으로 방문여부를 저장할 수 있게 만들었고, 방문하지 않은 경우, 연결된 모든 컴퓨터를 방문하는 식으로 재귀적으로 dfs를 호출하여 모두 방문할 때까지 계속해서 반복하였습니다.
---
- 깊이 우선 탐색 알고리즘(DFS, Depth-First Search): 하나의 정점부터 시작하여 아래로 깊게 내려가며 탐색
- 너비 우선 탐색 알고리즘(BFS, Breadth-First Search): 시작노드와 인접한 모든 노드부터 확인하는 알고리즘

a-honey / 2주차 / 4문제

---

woohyunkim/binary_search/Immigration.java
woohyunkim/dynamic_programming/N.java

Woohyunkim

---

donggyun/binary_search/입국심사.js
donggyun/dynamic_programming/N으로_표현.js
donggyun/dynamic_programming/등굣길.js
donggyun/dynamic_programming/정수_삼각형.js

* 5가 사용되는 횟수를 기준으로 2차원 배열 완성
* 찾는 값이 있다면 사용 횟수 반환
* 위치 기반 2차원 배열을 생성
* 위쪽 값과 왼쪽값을 더한 값이 현재까지 오는 경로의 경우의수
* 웅덩이가 있을 경우 현재 값을 0으로 채움
* 나머지 값을 저장하여 진행
* 삼각형을 2차원 배열로 변환
* 현재까지 내려오는 경우의 수들 중 최대값을 구하여 저장
* [i-1][j]와 [i-1][j-1] 중 최댓값을 구하여 현재값을 더한값을 반환

donggyun / 3주차 / 4문제

---

a-honey/binary_search/입국심사.py
a-honey/dynamic_programming/N으로_표현.py

a-honey / 3주차 / 2문제

---

imeureka/binary_search/입국심사.js
imeureka/hash/의상.js

> binary_search / Level 3
총 6 명          
a (7)   ㄱ  ㄷ              ㅁ             ㅂ 21 + 7 = 28이 최소 
b (10) ㄴ           ㄹ      (6분남음)ㅂ(이러면 10분기다려야되니까 30이 최소가 됨
00분            7분   10분   14분  20분  21분
이걸 어떻게 이분탐색으로,,?>? 분명 개념 이지했는데, 
우리가 구하고자 하는 키값은 모든 사람이 심사 걸리는 최솟값**
근데 어떤 수들이 있는거지 지금 7분 7분 6명다 요로콜롬 인 경우의 수를 생각해야되는건가??**
여기에서 막혀 일단 여기까지 구현해봤지만 실패가 나왔다. 그리고 구글링의 힘을 봐서 해결했다. 
-> times 배열의 최고 값을 기준으로 이분탐색하면서 mid 값으로 각 심사관이 몇명을 검색할 수 있냐만 계산하면 최소값을 구할 수 있었다.
> dp / Level 3

imeureka / 3주차 / 2문제

---

devjaeyoon/dynamic_programming/N으로 표현.js
devjaeyoon/graph/가장 먼 노드.js
devjaeyoon/heap/이중우선순위큐.js

>heap
>dynamic_programming
>graph

devjaeyoon / 3, 4주차 / 3문제

---

daeun/graph/순위.js
daeun/heap/더 맵게.js

**[PSG] 더 맵게 / Level 2** 
<hr>
**[PSG] 순위 / Level 3**
<hr>

daeun / 4주차 / 2문제

---

devjaeyoon/sort/H-Index.js
devjaeyoon/sort/K번째수.js

>K번째수
1. JavaScript의 slice 메소드를 사용하여 문제에 주어진 범위만큼 잘랐다(slice는 기존 배열에 영향을 주지 않는 메소드라 spread 연산자를 사용하여 복사하지 않아도 됨).
2. sort 메소드를 사용하여 정렬 후 조건에 해당하는 element를 answer 배열에 삽입
>H-Index
1. 논문의 수는 최대 1,000개, 논문별 인용 횟수는 최대 10,000회이므로 최대 10,000,000번의 연산을 할 수 있으니 O(N^2)의 코드를 작성할 수 있다.
2. i는 1부터 논문별 인용 횟수 배열의 요소 중 최댓값까지 반복을 진행하며 논문별 인용 횟수가 i보다 크다면 over 배열에 넣어 over 배열의 크기가 i보다 크거나 같을 경우(이상) H-Index 값이 될 수 있으므로 이를 저장.
3. H-Index는 가능한 최댓값이 H-Index가 되어야 하므로 계속 반복을 진행

devjaeyoon / 5주차 / 2문제

---

daeun/hash/폰켓몬.js
daeun/stack_queue/같은 숫자는 싫어.js

**[PSG] 폰켓몬 / Level 1** 
이 코드는 select 배열에 없는 폰켓몬 종류만 추가하고, 폰켓몬의 종류의 수가 N/2에 도달하면 중단하고 answer를 반환하도록 했다. 또한 선택한 폰켓몬 종류의 수가 N/2보다 작고 select 배열에 현재 폰켓몬 종류가 포함되어 있지 않다면 nums 배열에 추가해 계산하도록 문제를 풀었다.
<hr>
**[PSG] 같은 숫자는 싫어 / Level 1** 
현재 요소가 이전 요소와 다르면 추가하는 간단한 방식으로 풀었다. 문제가 쉬웠지만 기초를 탄탄히 하고 싶어서 낮은 단계부터 차근차근 풀어 볼 예정이다!
<hr>

daeun / 5주차 / 2문제

---

a-honey/brute_force/모의고사.js
a-honey/brute_force/소수찾기.js
a-honey/brute_force/최소_직사각형.js
a-honey/brute_force/카펫.js
a-honey/brute_force/피로도.js

가능한 모든 케이스를 검색하여 반환
각 높이와 너비를 순환하며 큰 값을 너비로, 작은 값을 높이로 설정해주고, 현재 width 값보다 크면 width값을 갱신해주고 최종적으로 가장 큰 명함의 크기를 반환하였습니다.
학생들의 답안 패턴을 2차원 배열로 저장한 후, 각각의 학생 답안을 문제의 길이만큼 순환하며 정답을 비교하였습니다. 초반에는 패턴을 인지하지 못해 문제 길이와 답안 길이를 비교하지 않았다가, 나머지를 활용하여 답안의 길이를 초과하는 경우를 추가하였습니다.
제곱근 아래의 모든 수를 반복문을 통해 나머지가 있는 지 확인하는 소수 판별 함수를 만들고, 주어진 배열의 모든 케이스를 반환하는 순열 반환 재귀 함수를 만들었습니다. 이후 순열 반환 재귀 함수의 각 요소들을 반복문을 통해 각 문자열 요소들도 set에 추가하여 반복을 제거한 이후 이후 소수 판별 함수를 통해 카운트하였습니다.
처음에는 단순히 격자의 개수를 더해 제곱근을 이용하여 너비와 높이를 구하였으나, 테스트에서 실패하였습니다. 이후 높이와 너비스에서 각각 2를 제거했을 때 yellow 격자의 개수가 나타나는 조건문을 추가하여 해결했습니다.
모든 케이스를 구해야하는 과정에서 파이썬의 permutations 함수를 직접 구현해야했고, 순환을 하면서 세번째 파라미터에 원본 요소가 들어오는 점을 이해하고, 재귀를 통해 완성할 수 있었습니다. 이후에는 각각의 케이스에 데해 for ... of, Array.forEach, Array.some의 차이를 이해하면서 각각의 케이스에 대해 카운트하였습니다.
- for...of: 배열이나 iterable을 순회. …

a-honey / 7주차 / 5문제

---

imeureka/graph/가장먼노드.js
imeureka/입문/각도기.js
imeureka/입문/두 수의 나눗셈.js
imeureka/입문/몫구하기.js
imeureka/입문/배열 두 배 만들기.js
imeureka/입문/배열의 평균값.js
imeureka/입문/분수의 덧셈.js
imeureka/입문/숫자 비교하기.js

> 입문 / Level 0
for 문 이용해서 간단하게 풀었는데 다른 풀이 방식도 있었다.
- reduce 함수를 잘 사용한 풀이법이 있어[ reduce 함수](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)참고하여 풀어보았다. 
```javascript
return numbers.reduce((a, b) => [...a, b * 2], []); 
``` 
원래 reduce는 하나의 값을 반환인데 배열의 값을 반환하고 싶으면 initValue에 배열을 넣어주면 되는 것 같다. 신기방기
-  map 사용 
``` javascript
const solution = (numbers) => return numbers.map((number) => number * 2);
``` 
>입문 / Level 0
이것 또한 reduce 함수를 통해 배열의 모든 값들을 더하고, 이를 배열의 요소로 나누어주면 됐다. 
평균값은.. 모든 요소 더한 값에 배열의 요소길이로 나눈 값.
> 입문 / Level 0
나는 switch case 문을 사용해서 풀어보았다. 하지만 다른 사람들의 풀이는 개간지였다. 삼항연산자 혹은 filter을 이용한 풀이도 멋있었다. 하지만 filter 풀이방식은 return 1234를 갯수로 응용해서 풀어서 이것보단 삼항연산자가 더 효율적인 풀이 방식 같아 공유한다. 
```javascript
return angle < 90 ? 1 : angle === 90 ? 2 : angle < 180 ? …
```

Imeureka / 8주차 / 3문제 

---

imeureka/입문/옷가게 할인받기.js
imeureka/입문/중앙값 구하기.js
imeureka/입문/짝수는 싫어요.js
imeureka/입문/최빈값 구하기.js
imeureka/입문/피자 나눠먹기.js

> 입문 / Level 0
정렬 `arr1.sort();` 이렇게 푸니까 정확도 100%는 아니였다.
- JS에서는 배열에 sort를 하면 정수형 원소도 문자열 기준으로 정렬 [1,200,3,40000,500].sort() => [1,200,3,40000,500] 대박~
- 그래서 (a,b)=>a-b라는 comparator가 필요
>입문 / Level 0
- 객체 {}는 키-값 쌍을 효율적으로 저장할 수 있으므로, 각 요소의 빈도수를 키로 접근하여 저장
> 입문 / Level 0
- 최대공약수 : let GCD = (num1,num2) => num2>0?GCD(num2, num1%num2):num1);
- 최소공배수 : let LCM = (num1*num2) / GCD

Imeureka / 8주차 /  5문제 

---

imeureka/입문/문자열 뒤집기.js
imeureka/입문/배열 뒤집기.js
imeureka/입문/아이스 아메리카노.js
imeureka/입문/양꼬치.js
imeureka/입문/직각 삼각형 그리기.js
imeureka/입문/짝수 홀수 개수.js
imeureka/입문/특정 문자 제거하기.js

> 입문 / Level 0
```javascript
function solution(num_list) {
const evenLength = num_list.filter(n => n % 2 === 0).length;
return [evenLength, num_list.length - evenLength];
}
```
- filter() 메서드
함수의 테스트를 통과하는 배열을 모아서 새로운 배열을 만드는 메서드로 이 코드에서는 짝수의 길이를 구하기 위해 filter()를 사용한 후 .length를 사용하였구나

Imeureka/다시코테 1일차/3문제

---

imeureka/기초/같은 숫자는 싫어.js
imeureka/기초/카운트다운.js
imeureka/입문/세균증식.js
imeureka/입문/편지.js

> 입문 / Level 0
> 입문 / Level 0
> 입문 / Level 1
> 입문 / Level 1
1. ~~ (double tilde)
Math.floor와 같은 기능을 한다.
~는 비트 연산의 not이고, 숫자에 ~ 연산을 하면 소수점이 버려진다.
~~는 ~를 두 번 실행한 것으로, 숫자에 활용하면 원래 숫자에서 정수부분만 취할 수 있다.
수행 속도는 ~~가 가장 빠르다고 한다.
~~ > Math.floor() > parseInt
2. Math.trunc
Math.trunc()는 소수점 이하는 다 버린다. 
ex) Math.trunc(23.3) = 23, Math.trunc(-23.3) = -23
Math.floor()는 소수점을 내림한다. 
ex) Math.floor(23.3) = 23, Math.floor(-23.3) = -24가 된다. 
음수인 경우도 생각해서 소수점을 이하 수를 없애고 싶을때는 Math.trunc를 사용하는 것이 좋다.
* 요약 : runc 는 소수점 버리기 floor 은 내림

Imeureka / 다시코테 3일차 / 4문제
